title: Brais Darriba
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs
favicon_ico: "/DAM-DESARROLLO-APLICACIONES-MULTIPLATAFORMA.png"

url: https://just-the-docs.github.io

aux_links:
  Aula Virtual: https://www.edu.xunta.gal/centros/iesmurallaromana/aulavirtual/my/courses.php
